using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "RoomTypeContainer", menuName = "Scriptable Objects/RoomTypeContainer")]
public class SO_RoomTypeContainer : ScriptableObject
{
    // Stores rooms that can be generated normally
    [SerializeField] public List<SO_RoomType> initialRoomTypes;
    // Stores rooms that can only be generated by the other room combinations or specific grammars
    [SerializeField] public List<SO_RoomType> alteredRoomTypes;

    //public Dictionary<E_RoomTypes, SO_RoomType> enumToObjectDict;

    // To avoid repeatedly searching through a list, I create a dictionary linking the Enum to the related Scriptable Object
    // This allows me to use the enum for comparison and creating the room, and can then get additional data from the SO when needed.
    // public void LinkEnumToObject()
    // {
    //     enumToObjectDict = new Dictionary<E_RoomTypes, SO_RoomType>();

    //     for (int i = 0; i < totalRoomTypes.Count; i++)
    //     {
    //         Debug.Log("Room Type: " + totalRoomTypes[i].roomType);
    //         enumToObjectDict.Add(totalRoomTypes[i].roomType, totalRoomTypes[i]);
    //     }
    // }
    public int AllocateTagIDs(int startingIDValue)
    {
        int idIncrementer = startingIDValue;
        for (int i = 0; i < initialRoomTypes.Count; i++)
        {
            initialRoomTypes[i].tagID = idIncrementer++;
        }

        for (int i = 0; i < alteredRoomTypes.Count; i++)
        {
            initialRoomTypes[i].tagID = idIncrementer++;
        }

        // Return the value, as any other tag storage objects will need to start with this count
        return idIncrementer;
    }
}
